import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import './globals.css';
import GlobalStates from './GlobalStates';

const jost = Jost({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <GlobalStates>{children}</GlobalStates>
      </body>
    </html>
  );
}
